// Inline the operator avatar SVGs (ui-mockups/Avatars/) into public/avatars.js.
// - namespaces each SVG's internal filter id (all use id="g") so 4 copies can coexist in the DOM
// - strips the root <svg> width/height so each scales to its container (keeps viewBox)
// Run: bun scripts/build-avatars.ts
import { readFileSync, writeFileSync } from "node:fs";

const MAP: [string, string, string][] = [
  ["avatar-operator.svg", "OPERATOR", "op"],
  ["avatar-vult-3r.svg", "VULT-3R", "vlt"],
  ["avatar-nomad.svg", "NØMAD", "nmd"],
  ["avatar-spectre-9.svg", "SPECTRE-9", "sp9"],
];

// Interim differentiation: SPECTRE-9's delivered art is the same silhouette as OPERATOR (both
// cyan). Recolor its optic glow so the two read as different units until a distinct SPECTRE-9
// asset is generated. (The glow uses currentColor from the root <svg style="color:…">.)
const COLOR_OVERRIDE: Record<string, string> = { "SPECTRE-9": "#3ddc97" };

const out: Record<string, string> = {};
for (const [file, name, slug] of MAP) {
  let svg = readFileSync(`ui-mockups/Avatars/${file}`, "utf8").trim();
  svg = svg.replaceAll('id="g"', `id="g_${slug}"`).replaceAll("url(#g)", `url(#g_${slug})`);
  // strip width/height from the ROOT <svg …> tag only
  svg = svg.replace(/^<svg([^>]*)>/, (_m, attrs) => `<svg${attrs.replace(/\s(width|height)="[^"]*"/g, "")}>`);
  if (COLOR_OVERRIDE[name]) svg = svg.replace(/^(<svg[^>]*color:)#[0-9a-fA-F]+/, `$1${COLOR_OVERRIDE[name]}`);
  out[name] = svg;
}

writeFileSync(
  "public/avatars.js",
  "// NIGHT MARKET — operator avatars (inlined SVGs). Generated by scripts/build-avatars.ts\n" +
  "// Source: ui-mockups/Avatars/. Do not edit by hand — re-run the script.\n" +
  "export const AVATARS = " + JSON.stringify(out) + ";\n",
);
console.log("wrote public/avatars.js:", Object.keys(out).join(", "));
