// Extracts each card's illustration SVG from ui-mockups/Assets/ and writes
// public/card-art.js (good-key -> inlined SVG string). Re-run if the assets change:
//   bun run scripts/extract-card-art.ts
const MAP: Record<string, [string, string, string]> = {
  // key      -> [asset file, css var used inside the svg, replacement hex]
  diamond: ["card-ai-cores.html", "--core", "#00fff0"],
  gold: ["card-illegal-implants.html", "--core", "#f4ff5c"],
  silver: ["card-stolen-data.html", "--core", "#ff2e88"],
  cloth: ["card-pharma-contraband.html", "--core", "#8a6fd8"],
  spice: ["card-cracked-software.html", "--core", "#3ddc84"],
  leather: ["card-street-weaponry.html", "--core", "#d9603f"],
  camel: ["card-courier-drone.html", "--trim", "#4fc3d9"],
};

const out: Record<string, string> = {};
for (const [key, [file, varName, hex]] of Object.entries(MAP)) {
  const html = await Bun.file(`ui-mockups/Assets/${file}`).text();
  const m = html.match(/<svg[\s\S]*?<\/svg>/);
  if (!m) { console.error("no <svg> found in", file); continue; }
  let svg = m[0];
  svg = svg.replaceAll(`var(${varName})`, hex);
  // safety net: any other var() left over -> neutral muted color
  svg = svg.replaceAll(/var\(--[a-z-]+\)/g, "#566a84");
  // Strip intrinsic width/height from the ROOT <svg> tag only (keeps viewBox).
  // Fixed pixel sizes on the root SVG break flex/aspect-ratio sizing in the card well,
  // especially for non-square art — CSS should size it, viewBox preserves aspect ratio.
  const gt = svg.indexOf(">");
  const tag = svg.slice(0, gt).replace(/\s+width="[^"]*"/, "").replace(/\s+height="[^"]*"/, "");
  svg = tag + svg.slice(gt);
  if (!svg.includes("xmlns=")) svg = svg.replace("<svg", '<svg xmlns="http://www.w3.org/2000/svg"');
  out[key] = svg;
}

const js = `// Auto-generated by scripts/extract-card-art.ts from ui-mockups/Assets/ — do not edit by hand.\nexport const CARD_ART = ${JSON.stringify(out)};\n`;
await Bun.write("public/card-art.js", js);
console.log(`wrote public/card-art.js with ${Object.keys(out).length} illustrations`);
